
'use server';

/**
 * @fileOverview This file defines a Genkit flow for processing text-based queries and generating comprehensive answers using AI,
 * including conversational context.
 *
 * - processTextQuery - A function that handles the text query processing.
 * - ProcessTextQueryInput - The input type for the processTextQuery function.
 * - ProcessTextQueryOutput - The return type for the processTextQuery function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ConversationTurnSchema = z.object({
  user: z.string().describe('The user query.'),
  assistant: z.string().describe('The assistant response.'),
});
export type ConversationTurn = z.infer<typeof ConversationTurnSchema>;

const ProcessTextQueryInputSchema = z.object({
  query: z.string().describe('The current text-based question submitted by the student.'),
  history: z.array(ConversationTurnSchema).optional().describe('The history of the conversation so far.'),
});
export type ProcessTextQueryInput = z.infer<typeof ProcessTextQueryInputSchema>;

const ProcessTextQueryOutputSchema = z.object({
  answer: z.string().describe('The comprehensive answer generated by AI, considering conversation history.'),
});
export type ProcessTextQueryOutput = z.infer<typeof ProcessTextQueryOutputSchema>;

export async function processTextQuery(input: ProcessTextQueryInput): Promise<ProcessTextQueryOutput> {
  return processTextQueryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'processTextQueryPrompt',
  input: {schema: ProcessTextQueryInputSchema},
  output: {schema: ProcessTextQueryOutputSchema},
  prompt: `You are an AI assistant designed to provide comprehensive and contextually relevant answers to student questions.
  {{#if history}}
  Here is the conversation history:
  {{#each history}}
  User: {{{this.user}}}
  Assistant: {{{this.assistant}}}
  {{/each}}
  {{/if}}

  Based on the conversation history (if any) and the current question, provide a helpful answer.

  Current Question: {{{query}}}

  Answer: `,
});

const processTextQueryFlow = ai.defineFlow(
  {
    name: 'processTextQueryFlow',
    inputSchema: ProcessTextQueryInputSchema,
    outputSchema: ProcessTextQueryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
